import {
  BookOpen,
  Calculator,
  ChefHat,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  FileText,
  Flame,
  GraduationCap,
  Image,
  Landmark,
  LayoutTemplate,
  Lightbulb,
  Map as MapIcon,
  MessageCircle,
  MessageSquareText,
  PackageCheck,
  PenLine,
  QrCode,
  ShieldAlert,
  Smartphone,
  Tag,
  Users,
  UtensilsCrossed,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/constants";

export const ICON_MAP: Record<IconName, LucideIcon> = {
  Compass,
  ShieldAlert,
  Wallet,
  Clock,
  Users,
  GraduationCap,
  Map: MapIcon,
  Smartphone,
  PackageCheck,
  BookOpen,
  LayoutTemplate,
  Lightbulb,
  Calculator,
  Image,
  FileText,
  MessageSquareText,
  Landmark,
  QrCode,
  CreditCard,
  ClipboardList,
  PenLine,
  Tag,
  MessageCircle,
  ChefHat,
  UtensilsCrossed,
  Flame,
};
